### ISSUE TITLE
Face expressions on cer in gazebo

### ISSUE THREAD

**Issue by vvasco** [robotology/cer-sim#17]
The new branch `feat/face-expressions` extends the `cer.sdf` to include face expressions on the robot in `gazebo`, by attaching the [videoTexture plugin](https://github.com/robotology/gazebo-yarp-plugins/tree/master/plugins/videotexture) to the `head_link_visual` of the cer model.
The module `faceExpressionImage` has to be run and `/faceExpressionImage/image:o` needs to be connected to `/SIM_CER_ROBOT::head_link::head_link_visual`.

Two issues were encountered:
- the `sim_cer_head.dae` had to be changed (thanks @aerydna), otherwise face expressions were not mapped correctly on the head;
- it seems that there is a conflict between the plugins of the cameras and the `videoTexture` plugin, as they open the same port `/SIM_CER_ROBOT::head_link::head_link_visual`. For this reason, I created a new model without the cameras.

cc @aerydna @fiorisi

**Comment by aerydna** [comment]
there is a meeting scheduled on May 30th with @fiorisi for integrating the cer head mesh mapping fix i've done in master. for the name conflict can you push the fix line i suggested yesterday @vvasco? does it worked?

**Comment by vvasco** [comment]
hi @aerydna, actually it did not work: with the fix line, the `name` parameter is used, but still two ports with the same name are opened.

**Comment by aerydna** [comment]
ok i'll check it out asap

**Comment by fiorisi** [comment]
cc @miggia

**Comment by vvasco** [comment]
Hi @aerydna @fiorisi, what's the status of this issue?

**Comment by pattacini** [comment]
@aerydna @fiorisi we need to progress on this; it'getting quite important.

**Comment by fiorisi** [comment]
As discussed with @aerydna, we agreed to simply merge the modification from [your branch](https://github.com/robotology/cer-sim/tree/feat/face-expressions) into the `master` branch.   
Before merging, it would be nice if you can please perform a test. A screenshot of the simulation is enough to validate the fix.

For future modifications, it is important to remember that the models (URDF or SDF) are the product of a generation process, which was implemented in [this script](https://github.com/robotology/cer-sim/blob/master/generate_models.py) (now not working).

**Comment by vvasco** [comment]
Hi @fiorisi @aerydna, it seems that the second problem mentioned initially is not there anymore (I'm trying to trace back which commit solved this):

> it seems that there is a conflict between the plugins of the cameras and the videoTexture plugin, as they open the same port /SIM_CER_ROBOT::head_link::head_link_visual. For this reason, I created a new model without the cameras.

Therefore, I'm doing some modifications in my branch in order to remove the `cer_no_cameras` model (not needed anymore) and include the video texture in the `cer` model.

**Comment by pattacini** [comment]
@vvasco opened up the corresponding PR in #18.
